routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

	Route::group(['middleware' => ['auth']], function () {

		
		Route::get('/home', 'HomeController@index')->name('home');
	

		Route::resources([
	
			
			'product_category' => 'ProductCategoryController',
			'products' => 'ProductController',
			'member_category' => 'MemberCategoryController',
			'members'=> 'MemberController',
			'transactions'=>'TransactionController'
		]);

   	});
	

	Auth::routes();

		

	

app/ProductCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProductCategory extends Model
{
    //
}

app/Http/Controllers/ProductCategoryController.php
<?php

namespace App\Http\Controllers;

use App\ProductCategory;
use Illuminate\Http\Request;

class ProductCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $category = ProductCategory::all();
        return view('product_category.index',compact('category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product_category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $category = new ProductCategory;

        $category->name = $request->name;
        $category->desc = $request->desc;
        $category->save();

        return redirect()->route('product_category.index');    
    }     

    /**
     * Display the specified resource.
     *
     * @param  \App\ProductCategory  $productCategory
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ProductCategory  $productCategory
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = ProductCategory::findOrFail($id);
        return view('product_category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ProductCategory  $productCategory
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = ProductCategory::findOrFail($id);
        $category->name = $request->name;
        $category->desc = $request->desc;
        $category->update();

        return redirect()->route('product_category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ProductCategory  $productCategory
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = ProductCategory::findOrFail($id);
        $category->delete();
        return redirect()->route('product_category.index');
    }
}

resources/views/product_category/create.blade.php
@extends('layouts.template')

@section('content')

<div class="card">
  <div class="card-header">
   <h4> Tambah Kategori Produk</h4>
  </div>
  <div class="card-body">
    <form action="{{route('product_category.store') }}" method="post">
            @csrf
                <div class="form-row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="name">Nama</label>
                            <input type="text" name="name" class="form-control" 
                            id="name" placeholder="Masukkan Nama" required>
                        </div>
                        <div class="form-group">
                            <label for="desc">Deskripsi</label>
                            <textarea class="form-control" id="desc" name="desc" 
                             rows="4" required></textarea>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-danger">Tambah</button>
        </form>
    </div>
  </div>
</div>
@endsection

resources/views/product_category/edit.blade.php
@extends('layouts.template')

@section('content')

<div class="card">
  <div class="card-header">
   <h4> Ubah Kategori Produk</h4>
  </div>
  <div class="card-body">
    <form action="{{route('product_category.update', $category->id) }}" method="post">
            @csrf
            @method('put')
                <div class="form-row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="name">Nama</label>
                            <input type="text" name="name" class="form-control" 
                            id="name" value="{{ $category->name }}">
                        </div>
                        <div class="form-group">
                            <label for="desc">Deskripsi</label>
                            <textarea class="form-control" id="desc" name="desc" 
                             rows="4" required value="{{ $category->desc }}"></textarea>
                             <!-- <input type="text" name="desc" class="form-control" 
                            id="desc" value="{{ $category->desc }}"> -->
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-success">Simpan</button>
        </form>
    </div>
  </div>
</div>
@endsection

resources/views/product_category/index.blade.php
 @extends('layouts.template')

@section('content')

 <div class="col-lg-12 stretch-card">
                <div class="card">
                  <div class="card-body">
                    <h2 class="title-12 m-b-0">Kategori Produk</h2>

                    <div class="table-data__tool">
                        <div class="table-data__tool-left">
                        </div>
                        <div class="table-data__tool-right">
                            
                            <div class="rs-select2--dark rs-select2--sm rs-select2--dark2">
                               <a href="{{ route('product_category.create') }}">
                            <button class="au-btn au-btn-icon au-btn--blue au-btn--small">Tambah</button></a>
                                <div class="dropDownSelect2"></div>
                            </div>
                        </div>
                     </div>
                 
                    <table class="table table-bordered">
                      <thead>
                        <tr>
                          <th> No </th>
                          <th> Nama </th>
                          <th> Deskripsi </th>
                          
                         
                        </tr>
                      </thead>
                      <tbody>
                        @foreach($category as $i => $item)
                        <tr class="table-info">
                          <td>{{$i+1}}</td>
                          <td>{{$item->name}}</td>
                          <td>{{$item->desc}}</td>
                            <td>
                              <div class="table-data-feature">
                               <form action="{{ route('product_category.destroy',$item->id) }}" method="post">

                                <a href="{{ route('product_category.edit',$item->id) }}">
                                <button class="btn btn-success" type="submit" title="Edit">
                                    <i class="zmdi zmdi-edit"></i>
                                </button>
                                </a>
                                @csrf
                                @method('delete')
                                <button type="submit" class="btn btn-danger"  title="Delete"
                                onclick="return comfirm('yakin?')">
                                    <i class="zmdi zmdi-delete"></i>
                                </button>
                                </form>
                              </div>
                            </td>
                        </tr>
                        @endforeach
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>

              @endsection 